---
- name: Install RPM packages
  dnf:
    name:
      - ipa-client
      - python3-pip
    state: present

- name: Enroll system as IPA client
  shell: ipa-client-install --hostname {{ ansible_fqdn }} --domain tinystage.test --realm {{ krb_realm }} --server ipa.tinystage.test -p {{ ipa_admin_user }} -w {{ ipa_admin_password }} -U -N --force-join
  args:
    creates: /etc/ipa/default.conf

# Trust IPA's CA

- name: Get the content of the CA cert
  slurp:
    src: /etc/ipa/ca.crt
  register: ca_crt

- name: Install certifi
  pip:
    name: certifi

- name: Get the CA certs file from certifi
  command: python3 -m certifi
  register: certifi_cacert
  become: yes
  become_user: vagrant

- name: Put tinystage root CA in the list of CA's for certifi
  blockinfile:
    block: "{{ ca_crt.content | b64decode }}"
    path: "{{ certifi_cacert.stdout }}"




- name: kinit for nonbot
  shell: echo "{{ipa_admin_password}}" | kinit {{ ipa_admin_user }}@{{ krb_realm }}

- name: Delete any old service in IPA
  command: ipa service-del MATRIXBOTS/matrixbots.tinystage.test
  ignore_errors: yes

- name: Create the service in IPA
  command: ipa service-add --force MATRIXBOTS/matrixbots.tinystage.test

- name: Get service keytab for NONBOT
  shell: ipa-getkeytab -p MATRIXBOTS/matrixbots.tinystage.test@{{ krb_realm }} -k /var/lib/gssproxy/matrixbots.keytab
  args:
    creates: /var/lib/gssproxy/matrixbots.keytab

- name: Set the correct permissions on keytab
  file:
    path: /var/lib/gssproxy/matrixbots.keytab
    owner: root
    group: root
    mode: 0640

- name: Copy gssproxy conf
  copy:
    src: gssproxy-matrixbots.conf
    dest: /etc/gssproxy/98-matrixbots.conf
    mode: 0644
    owner: root
    group: root

- name: Enable and restart GSSProxy
  systemd:
    state: restarted
    name: gssproxy
    enabled: yes
    daemon_reload: yes
